# Stage 1: Build the React application
FROM node:18-alpine as builder

WORKDIR /app

COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm install

COPY frontend/ .
RUN npm run build

# Stage 2: Create the final image with Nginx
FROM nginx:1.21.3-alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
