name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Clear pip cache
      run: pip cache purge

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r backend/requirements.txt
        pip install -e .

    - name: Install frontend dependencies
      run: npm install --prefix frontend

    - name: Run backend tests
      run: |
        export PYTHONPATH=.
        python -m pytest

    - name: Run frontend tests
      run: npm test --prefix frontend -- --watchAll=false

    - name: Build Docker images
      run: docker compose build